cricket/urls.py
from django.contrib import admin
from django.urls import path,include
import mi,rr

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mi/',include('mi.urls')),
    path('rr/',include('rr.urls')),
]

mi/urls.py
from django.urls import path
from mi.views import *
app_name='mi'
urlpatterns=[
    path('rohith/',rohith,name='rohith'),
]

rr/urls.py
from django.urls import path
from rr.views import *
app_name='rr'
urlpatterns=[
    path('sanju/',sanju,name='sanju'),
]

mi/models.py
from django.db import models

# Create your models here.

rr/models.py
from django.db import models

# Create your models here.

mi/views.py
from django.shortcuts import render

# Create your views here.
def rohith(request):
    return render(request,'rohith.html')

rr/views.py
from django.shortcuts import render

# Create your views here.
def sanju(request):
    return render(request,'sanju.html')

templates/rohith.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <CENTER>
        <h1 style="background-color: blue;">WELCOME TO MUMBAI INDIANS </h1>
        <h1 style="color: rgb(75, 75, 239);">Rohith Sharma</h1>
        <a href="{% url 'rr:sanju' %}"><h3>go to RAJASTHAN</h3></a>
    </CENTER>
</body>
</html>

templates/sanju.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="background-color: cornflowerblue;">WELCOME TO RAJASTHAN ROYAL'S</h1>
        <h1 style="color: rgb(132, 250, 14);">SAnju Samson </h1>
        <a href="{% url 'mi:rohith' %}"><h3>go to MUMBAI</h3></a>
    </center>
</body>
</html>